# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
minecraft_version = 26.3-snapshot-10
loader_version = 0.19.3

# Mod Properties
mod_version = 1.2.0
maven_group = justfatlard.player_trade
archives_base_name = player-trade

# Dependencies
fabric_version = 0.158.2+26.3
